import Head from 'next/head'
import { HomePage } from '../components'
import { Box } from '../common'

export default function Home() {
    return (
        <>
            <Head>
                <title>Codebridge Test</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Box sx={{ minHeight: '100vh' }}>
                <HomePage />
            </Box>
        </>
    )
}
